export type Shortcut = { keys: string[]; action: string; group: string };

export const SHORTCUTS: Shortcut[] = [
  { group: "Playback", keys: ["Space"], action: "Play / pause" },
  { group: "Playback", keys: ["Esc"], action: "Stop" },
  { group: "Playback", keys: ["L"], action: "Toggle loop" },
  { group: "Playback", keys: ["Home"], action: "Go to start" },
  { group: "Playback", keys: ["End"], action: "Go to end" },
  { group: "Playback", keys: ["←", "→"], action: "Skip 1 s" },
  { group: "Playback", keys: ["Shift", "← / →"], action: "Skip 5 s" },
  { group: "Playback", keys: ["Alt", "← / →"], action: "Skip 0.2 s" },
  { group: "View", keys: ["F"], action: "Follow playhead" },
  { group: "View", keys: ["+", "=", "]"], action: "Zoom in" },
  { group: "View", keys: ["-", "["], action: "Zoom out" },
  { group: "View", keys: ["0"], action: "Show entire recording" },
  { group: "View", keys: ["PageDown"], action: "Next page" },
  { group: "View", keys: ["PageUp"], action: "Previous page" },
  { group: "View", keys: ["1–5"], action: "Window 2 / 5 / 10 / 30 / 60 s" },
  { group: "View", keys: ["Wheel"], action: "Zoom around cursor" },
  { group: "View", keys: ["Shift", "Wheel"], action: "Pan" },
  { group: "View", keys: ["Click overview"], action: "Seek" },
  { group: "View", keys: ["Drag window"], action: "Pan the editor" },
  { group: "Review", keys: ["A"], action: "Annotate tool" },
  { group: "Review", keys: ["C"], action: "Caliper" },
  { group: "Review", keys: ["H"], action: "Hide / show annotations" },
  { group: "Review", keys: ["D"], action: "Show / hide DSA spectrogram" },
  { group: "Review", keys: ["B"], action: "Color traces by hemisphere or Hz" },
  { group: "Review", keys: [",", "<"], action: "Bigger waves (more sensitive)" },
  { group: "Review", keys: [".", ">"], action: "Smaller waves (less sensitive)" },
  { group: "Review", keys: ["Click (annotate)"], action: "Drop a marker" },
  { group: "Tracks", keys: ["S"], action: "Solo this track (multi-solo)" },
  { group: "Tracks", keys: ["M"], action: "Mute this track" },
  { group: "Tracks", keys: ["Double-click S"], action: "Exclusive solo" },
  { group: "Help", keys: ["?"], action: "Keyboard shortcuts" },
];
